### ISSUE TITLE
Refactor please

### ISSUE THREAD

**Issue by temi92** [temi92/ALPR-capture#5]
We need to avoid doing things like this please.
https://github.com/temi92/ALPR-capture/blob/80acea58fe64ac2fd538bfda19d3bc415dc6a2ef/plate_reader/run_tests.py#L72

**Comment by abbasegbeyemi** [comment]
Yeah I agree, I’m assuming the command line version would work better. However if we aren’t using a command line, or gui, what’s the alternative?
